exam/urls.py
from django.contrib import admin
from django.urls import path, include

from exam import views

app_name = 'exam'
urlpatterns = [
    path('mark/exam=<int:exam>/student=<int:student>', views.calculate_mark, name='calculate_mark'),
    path('exam/exam_id=<int:pk>', views.take_exam, name='take_exam'),
    path('review/exam_id=<int:exam>/student=<int:student>', views.review_exam, name='review_exam'),
    path('exam/pdf/exam_id=<int:exam>', views.generate_pdf, name='generate_pdf'),
    path('admin/exam/question/add_questions', views.add_questions, name="add_questions"),
    path('', views.main, name='main'),
]

exam_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.site.site_header = 'Admin Panel'
admin.site.site_title = 'Admin Panel'
admin.site.site_url = 'https://github.com/albatros-21'
admin.site.index_title = 'Admin Panel'
admin.empty_value_display = '**Empty**'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('exam.urls')),
]

if settings.DEBUG: # new
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path, include

from user import views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

exam/models.py
from django.db import models
from user.models import Year, Student
import datetime
from django.utils import timezone



class Answer(models.Model):
    student_id = models.IntegerField()
    qs_id = models.IntegerField()
    choice_id = models.IntegerField()
    exam_id = models.IntegerField()


        
    def __str__(self):
        return str(self.student_id) +" - " + str(self.qs_id) 

class Exam(models.Model):

    exam_name = models.CharField(max_length=150)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    total_marks = models.IntegerField(default=0)
    start_date_time = models.DateTimeField(blank=True, null=True)
    end_date_time = models.DateTimeField(blank=True, null=True)
    total_time = models.IntegerField(default=0, help_text="Enter in minutes")
    active = models.BooleanField(default=False, blank = True)
    assigned = models.ManyToManyField(Student)




    class Meta:
        ordering = ('start_date_time','exam_name')

        db_table = 'sınavlar'
        
    def __str__(self):
        return self.exam_name

    def is_past_due(self):
        if datetime.date.today() > self.start_date_time():
            return True
        return False




class Question(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    correct_answer = models.IntegerField(default=1)
    cover = models.ImageField(upload_to='images/questions/', default = None, blank=True, null=True)

    def __str__(self):
        return self.question_text 

    def getChoices(self):
        return Choice.objects.filter(question = self)

    def getChoiceImage(self):
        return ChoiceImage.objects.filter(question = self)
        ch = ChoiceImage.objects.filter(question = self).count()
        if ch != 0:
            return ChoiceImage.objects.filter(question = self)
        else:
            return False

    choice = property(getChoices)
    choiceImage = property(getChoiceImage)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    def __str__(self):
        return self.choice_text

class ChoiceImage(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_cover = models.ImageField(upload_to='images/choices/', default = None, blank=True, null=True)

    def __str__(self):
        return str(self.id)

class Mark(models.Model):
    student_id = models.IntegerField(default=1)
    exam_id = models.IntegerField(default=1)
    mark = models.IntegerField(default=1)

    def __str__(self):
        return str(self.student_id) + " - " + str(self.mark)

exam/views.py
from datetime import timedelta


from django.db.models.functions import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.views.generic import ListView

from exam.models import Exam, Question, Choice, Answer, Mark
from user.models import Student

from user.forms import LoginForm

from math import ceil

#Headers to generate pdf ReportLab
from django.http import FileResponse
from io import BytesIO
from reportlab.platypus import SimpleDocTemplate, Paragraph, PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm, inch
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from textwrap import wrap
from reportlab.lib.utils import ImageReader
from django.db.models import Q



def main(request):
    if 'username' in request.COOKIES:
        username = request.COOKIES['username']
        smail = Student.objects.filter(email_id__iexact=username, )
        year = smail.values('year')
        sid = smail.values('id')[0]
        answer = Answer.objects.filter(student_id=sid['id'])
        exam_id = answer.values('exam_id').distinct()



    else:
        return redirect('user:login')


    for y in year:
        exam = Exam.objects.filter(year__year = y['year'], start_date_time__date=timezone.now(),
                                   start_date_time__lte=datetime.datetime.now(), end_date_time__gte=datetime.datetime.now())

        #exam = Exam.objects.exclude(pk__in = exam_id)
    attended_exam = Exam.objects.filter(pk__in = exam_id)

    return render(request, 'exam/main.html', {'username': username, 'exam':exam, 'attended_exam': attended_exam, 'student':smail})

def take_exam(request, pk):
    if request.method == "POST":
        username = request.COOKIES['username']

        smail = Student.objects.get(email_id__iexact=username, )
        user_id = smail.id

        question_id_list = []
        questions_list = Question.objects.filter(exam__pk=pk, )

        for word in questions_list:
            question = Question.objects.get(question_text=word,)
            a = question.id
            question_id_list.append(a)

        i = 1
        while i <= len(question_id_list):
            #print(user_id, question_id_list[i-1], request.POST[str(i)], pk)
            answer = Answer(student_id=user_id, qs_id = question_id_list[i-1], choice_id= request.POST[str(i)], exam_id = pk)
            answer.save()
            i+=1
        
        return redirect('exam:calculate_mark', exam=pk, student= user_id)

    if 'username' in request.COOKIES:
        username = request.COOKIES['username']
        smail = Student.objects.filter(email_id__iexact=username, )
        sid = smail.values('id')[0]
        answer = Answer.objects.filter(student_id=sid['id'], exam_id=pk).count()

        if answer == 0:
            exam_details = Exam.objects.filter(pk= pk )

            questions_set = Question.objects.filter(exam__pk= pk )

            return render(request, 'exam/exam.html', {'question_set':questions_set, 'student': smail, 'exam_details':exam_details})
        else:
            return redirect('exam:main')
    else:
        return redirect('user:login')

def calculate_mark(request, exam, student):
    answer = Answer.objects.filter(exam_id = exam, student_id = student )
    exam_object = Exam.objects.filter(pk = exam)
    mark = 0
    for ans in answer:
        ques = Question.objects.filter(pk = ans.qs_id )
        for qs in ques:
            correct_choice = qs.correct_answer
            if correct_choice == ans.choice_id:
                mark += 4

    marks = Mark(student_id= student,  exam_id = exam, mark = mark)
    marks.save()

    if 'username' in request.COOKIES:
        username = request.COOKIES['username']
        smail = Student.objects.filter(email_id__iexact=username, )
        year = smail.values('year')
    else:
        return redirect('user:login')

    return render(request, 'exam/mark.html', {'username': username, 'exam':exam_object, 'student':smail, 'mark':mark})

def add_questions(request):
    if request.method == "POST":
        exam_name = request.POST.get('exam', "")
        qs_list = request.POST.get('qs', "")
        exam = Exam.objects.values_list('exam_name', flat=True)
        if exam_name not in exam:
            exam = Exam.objects.all()
            return render(request, 'exam/questions.html', {'exam':exam})
        
        exam_object = Exam.objects.get(exam_name= exam_name, )
        i = 0
        for text in qs_list.split("\n"):
            if i == 0:
                qs_text = str.strip(text)
                i = 1
                continue
            if i == 1:
                crct_ans = int(text)
                i = 2
                qs_object = Question.objects.create(exam= exam_object, question_text= qs_text, correct_answer = crct_ans)
                continue
            if len(text.strip()) == 0:
                i = 0
                continue
            choice_text = str.strip(text)
            choice_object = Choice.objects.create(question= qs_object, choice_text = choice_text)
        
        return redirect('admin:index')

    exam = Exam.objects.all() #filter(student.year=exam.year)
    return render(request, 'exam/questions.html', {'exam':exam})

def generate_pdf(request, exam):
    exam_details = Exam.objects.filter(pk= exam )
    question_list = Question.objects.filter(exam__pk= exam, )

    response = HttpResponse(content_type='application/pdf')


    # Create a file-like buffer to receive PDF data.
    buffer = BytesIO()

    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer, pagesize=A4)

    p.setFont('Helvetica', 36)
    for word in exam_details.values('exam_name'):
        exam_name = word['exam_name']
        p.drawString(75, 750, exam_name)

    response['Content-Disposition'] = 'attachment; filename="'+exam_name+'.pdf"'

    x = 75
    y = 750
    i = 1
    page_number = 1
    PAGE_BREAK_COORDINATE = 150
    HORIZONTAL_WORD_LIMIT = 55

    for word in question_list.values('question_text'):
        if y < PAGE_BREAK_COORDINATE:
            p.setFont('Helvetica', 15)
            p.drawString(300, 40, str(page_number))
            page_number+=1
            p.showPage()
            y = 820
        p.setFont('Helvetica', 16)
        y -= 40
        t = p.beginText()
        t.setTextOrigin(x,y)
        qs_text = str(i) + ") "+ word['question_text']
        wraped_text = "\n".join(wrap(qs_text, HORIZONTAL_WORD_LIMIT))
        t.textLines(wraped_text)
        n = int(ceil(len(qs_text) / HORIZONTAL_WORD_LIMIT))
        p.drawText(t)
        i+= 1

        #qs_cover = ImageReader(word['cover'].url)
        #canvas.drawImage(qs_cover, 100, 100, mask='auto')
        question = Question.objects.get(question_text= word['question_text'], )
        a = question.id
        choice_list = Choice.objects.filter(question__pk = a)
        y-= (15*n)
        j = 1
        for choice in choice_list.values('choice_text'):
            p.setFont('Helvetica', 14)
            y-= 25
            p.drawString(x, y, "     " + str(j) + ") "+ choice['choice_text'])
            j += 1
    if y >= PAGE_BREAK_COORDINATE:
        p.setFont('Helvetica', 15)
        p.drawString(300, 40, str(page_number))


    # Close the PDF object cleanly, and we're done.
    p.save()

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.

    #buffer.seek(0)

    #del(request.env['wsgi.file_wrapper'])
    #w = FileWrapper(buffer)
    #content_type = self.object.mimetype or 'application/octet-stream'
    #response = http.FileResponse(buffer, content_type=content_type)
    #if self.object.encoding:
        #response['Content-Encoding'] = self.object.encoding
    #response['Cache-Control'] = 'public, max-age=31536000'
    #return response
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response
    #return FileResponse(buffer, as_attachment=True, filename=exam_name+'.pdf')

def review_exam(request, exam, student):

    answer = Answer.objects.filter(exam_id=exam, student_id=student )
    correct_answer = []
    for ans in answer:
        ques = Question.objects.filter(pk = ans.qs_id )
        for qs in ques:
            correct_choice = qs.correct_answer
            correct_answer.append(correct_choice)
            

    username = request.COOKIES['username']
    smail = Student.objects.filter(email_id__iexact=username, )

    exam_details = Exam.objects.filter(pk= exam )

    questions_list = Question.objects.filter(exam__pk= exam, )
    question_set = {}

    for word in questions_list:
        question = Question.objects.get(question_text= word, )
        a = question.id
        answer_list = Choice.objects.filter(question__pk = a)
        question_set[word] = list(answer_list)
    answers = zip(answer,correct_answer)
    return render(request, 'exam/review.html', {'question_set':question_set, 'student': smail, 'exam_details':exam_details, 'answer':answers})

exam/templates/exam/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
        <title>
            {% block title %} Oes {% endblock %}
        </title>
        <style>
            .oes-masthead {
                background-color: #EEEEEE;
                margin-bottom: 1em;
            }
        </style>

        {% block headers %} {% endblock %}
    </head>
    <body>
        <div class="oes-masthead">
            <div class="container">
                <nav class="nav">
                    <div class="navbar-brand">College Name</div>
                    <a class="nav-link" href="#">Profile</a>
                </nav>
            </div>
        </div>

        <div class='container'>
            <div class="row">
                <div class="col-sm-8 mymdb-main">
                    {% block main %} {% endblock %}
                </div>
                <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
                    {% block sidebar %} {% endblock %}
                </div>
            </div>
        </div>
    </body> 
</html>

exam/templates/exam/exam.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
        <!-- Font special for pages-->
        <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <title>
            Exam
        </title>

        {% load staticfiles %}
        <link href="{% static 'exam/css/exam.css' %}" rel="stylesheet" media="all">
    </head>
    <body>
        <div class="oes-masthead">
            <div class="container">
                <nav class="nav">
                    <div class="navbar-brand">College Name</div>
                </nav>
            </div>
        </div>
        
        <div class="student-details">
            <div class='container-fluid'>
              <div class="row student-row">
                  {% for st in student %}
              <div class="col-sm-8">
                  <p class="detail-fields"> Name: {{ st.first_name }} {{ st.last_name }}</p>
                  <p class="detail-fields"> Year: {{ st.year }}</p>
                  {% endfor %}
                  {% for exam in exam_details %}
                  <p class="detail-fields"> Exam Name: {{ exam.exam_name }}</p>
                  <p class="detail-fields"> Exam Date: {{ exam.start_date_time }}</p>
                  <p class="detail-fields"> Exam E-Date: {{ exam.end_date_time }}</p>
                  {% endfor %}
              </div>
              <div class="col-sm-4">
                <p class="timer">Duration: </p>
                <p id="demo" class="timer"> </p>
              </div>
            </div>
          </div>
        </div>

        <div class='container-fluid qs-container'>
            <div class="row qs-row">
                <div class="col-sm-8 page-wrapper">
                  <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}      
                            {% for qs in question_set %}
                            <div class="qs" id="{{ forloop.counter }}">
                                <p class="display-4 qs-no">Question No: {{ forloop.counter }}</p>
                                <hr>
                                <br>
                                <p class="display-4 ques">{{ forloop.counter }}) {{ qs.question_text }}</p>
                                {% if qs.cover %}
                                  <div class="qs_cover">
                                    <img src="{{ qs.cover.url }}"  >
                                  </div>
                                {% endif %}
                                
                                {% for ans in qs.choiceImage %}
                                  {% if ans %}
                                    <div class="ans_cover">
                                      <img src="{{ ans.choice_cover.url }}"  > 
                                    </div> 
                                  {% endif %}
                                {% endfor %}
                                {% for ans in qs.choice %}
                                    <div class="answer">
                                    <input class="radio" type="radio" name="{{ forloop.parentloop.counter }}" value="{{ forloop.counter }}" checked>  {{ forloop.counter }})  {{ ans.choice_text }}<br>
                                  </div>
                                {% endfor %}
                            </div>
                            {% empty %}
                                <p> No questions </p>
                            {% endfor %}
                            <div class="submit-container">
                            <input class="btn btn-success submit" id="submit" type="submit" value="Submit">
                            </div> 
                        </form> 
                  </div>
                      <div class="qs-buttons">
                        <button id="btn-left" class="btn btn-secondary btn-left" onclick="plusDivs(-1, 2)">&#10094; Previous</button>
                      <button id="btn-right" class="btn btn-secondary btn-right" onclick="plusDivs(1, 1)">Next &#10095;</button>
                      <button id="btn-right" class="btn btn-warning btn-right" onclick="plusDivs(1, 0)">Save &#10095;</button>
                    </div>
                    </div>
                  <div class="col-sm-3 offset-sm-1 side-bar">
                      <div class="button-container">
                        {% for qs in question_set %}
                        <button id="btn-left" class="btn btn-secondary btn-nav" onclick="jumpDivs({{ forloop.counter }})"> {{ forloop.counter }}</button>
                        {% endfor %}
                      </div>
                  </div>
              </div>
          </div>
      </body> 

      <script>
        
    //To disable right click
    document.addEventListener('contextmenu', event => event.preventDefault());


  //Slideshow creator
  var slideIndex = 1;
  showDivs(slideIndex);
  
  function jumpDivs(n) {
    showDivs(n, 2);
  }
  function plusDivs(n, op) {
    showDivs(slideIndex += n, op);
  }
  
  function showDivs(n, op) {
    var i;
    var x = document.getElementsByClassName("qs");
    var nav_btn = document.getElementsByClassName("btn-nav");

    if (op == 0) {
      nav_btn[n-2].classList.remove('btn-secondary');
      nav_btn[n-2].classList.remove('btn-warning');
      nav_btn[n-2].classList.add('btn-success');
    }
    if (op == 1) {
      nav_btn[n-2].classList.remove('btn-secondary');
      nav_btn[n-2].classList.remove('btn-success');
      nav_btn[n-2].classList.add('btn-warning');
    }
    var button = document.getElementById("submit");
    slideIndex = n;
    if (n > x.length) {slideIndex = 1}
    if (n < 1) {slideIndex = x.length}
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";  
    }
    button.style.display = "none"

    if ( document.getElementById("btn-right").classList.contains('disabled') ) {
      document.getElementById("btn-right").classList.remove('disabled');
    }

    if (n==x.length ||  n == 0) {
      button.style.display = "inline"
      document.getElementById("btn-right").classList.add('disabled');
    }

    if ( document.getElementById("btn-left").classList.contains('disabled') ) {
      document.getElementById("btn-left").classList.remove('disabled');
    }

    if (n==1) {
      document.getElementById("btn-left").classList.add('disabled');
    }

    
    x[slideIndex-1].style.display = "block";  
  }


    //Counter generator 
      {% for exam in exam_details %}
      // eslint-disable-next-line [RULE]
      var counter = {{ exam.total_time }} * 60
      {% endfor %}
      if (sessionStorage.getItem("counter") != null  ){
              counter = sessionStorage.getItem("counter")-1
              sessionStorage.setItem("counter", counter);
      }
      else {
          sessionStorage.setItem("counter", counter);
      }
      var x = setInterval(function() {
  
          counter = sessionStorage.getItem("counter");
  
          var hour = Math.floor(counter / 3600);
          var min = Math.floor((counter - hour * 3600)/60); 
          var sec = (counter - hour * 3600 - min * 60);
      
          
        // Output the result in an element with id="demo"
        document.getElementById("demo").innerHTML = hour + "h "
        + min + "m " + sec + "s ";
      
       counter--;
       sessionStorage.setItem("counter", counter);
          
        // If the count down is over, write some text 
        if (counter < 0) {
          document.getElementById("demo").innerHTML = "EXPIRED";
          var button = document.getElementById('submit').click();
        }
      }, 1000);
      </script>
  </html>

exam/templates/exam/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <title>
                {% for st in student %}
                    {{ st.first_name }} {{ st.last_name }} - Home
                {% endfor %}
        </title>

        {% load static %}

        <!-- Main CSS-->
        <link href="{% static 'exam/css/main.css' %}" rel="stylesheet" media="all">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Font special for pages-->
        <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    </head>

    <body>
        <div class="oes-masthead">
            <div class="container">
                <nav class="nav">
                    <div class="navbar-brand">College Name</div>
                    <a class="nav-link" href="#">{{ username }}</a>
                    <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                </nav>
            </div>
        </div>

        <div class="container-fluid">

            <div class="row">
                
                <div class="col-sm-3" >
                    <div class="side-bar-wrapper">
                        {% for st in student %}
                            <p class="student-name">{{ st.first_name |title}} {{ st.last_name |title}} </p>
                            <p class="student-year">{{ st.year }} </p>
                        {% endfor %}
                    </div>
                </div>

                <div class="col-sm-9" >
                    <div class="page-wrapper">
                        <div class="card-body">
                            <p class="display-4">Exam list</p>
                            <br>
                            {% for ex in exam %}
                                <br>
                                <div class="exam-tag">
                                    <a class="exam-name" href="{% url 'exam:take_exam' pk=ex.id %}"> {{ ex.exam_name | title}} </a>
                                    <br>
                                    <br>
                                    <p> Total Mark : {{ ex.total_marks }}</p>
                                    <p> Duration : {{ ex.total_time }} minutes</p>
                                    <p> Starts on : {{ ex.start_date_time }}</p>
                                    <p> Ends on: {{ ex.end_date_time }} </p>
                                </div>
                                <br />
                            {% endfor %}
                        </div>
                        <div class="card-body">
                            <p class="display-4">Attended</p>
                            <br>
                            {% for ex in attended_exam %}
                                <br>
                                <div class="attended exam-tag">
                                    <a class="attended-name exam-name" href="{% url 'exam:take_exam' pk=ex.id %}"> {{ ex.exam_name | title}} </a>
                                    <br>
                                    <br>
                                    <p> Total Mark : {{ ex.total_marks }}</p>
                                    <p> Duration : {{ ex.total_time }} minutes</p>
                                    <div class="option-buttons">
                                        <a href="{% url 'exam:generate_pdf' exam=ex.id %}" class="btn btn-primary btn-left">Download</a>
                                        {% for st in student %}
                                        <a href="{% url 'exam:review_exam' exam=ex.id student=st.id %}" class="btn btn-danger btn-right">Review</a>
                                        {% endfor %}
                                    </div>
                                    <!-- <p> Starts on : {{ ex.start_date_time }}</p> -->
                                </div>
                                <br />
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

        

exam/templates/exam/mark.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <title>
                {% for st in student %}
                    {{ st.first_name }} {{ st.last_name }} - Home
                {% endfor %}
        </title>

        {% load static %}

        <!-- Main CSS-->
        <link href="{% static 'exam/css/mark.css' %}" rel="stylesheet" media="all">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Font special for pages-->
        <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    </head>

    <body>
        <div class="oes-masthead">
            <div class="container">
                <nav class="nav">
                    <div class="navbar-brand">College Name</div>
                    <a class="nav-link" href="#">{{ username }}</a>
                    <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                </nav>
            </div>
        </div>

        <div class="container-fluid">

            <div class="row">
                
                <div class="col-sm-3" >
                    <div class="side-bar-wrapper">
                        {% for st in student %}
                            <p class="student-name">{{ st.first_name }} {{ st.last_name }} </p>
                            <p class="student-year">{{ st.year }} </p>
                        {% endfor %}
                    </div>
                </div>

                <div class="col-sm-9" >
                    <div class="page-wrapper">
                        <div class="card-body">
                            <!-- <p class="display-4">You scored:</p> -->
                            <br>
                                <br>
                                {% for ex in exam %}
                                <div class="exam-tag">
                                    <a class="exam-name" href="{% url 'exam:main' %}"> {{ ex.exam_name }} </a>
                                    <br>
                                    <br>
                                    <p> You scored {{ mark }}/{{ ex.total_marks }}</p>
                                    <div class="option-buttons">
                                        <a href="{% url 'exam:generate_pdf' exam=ex.id %}" class="btn btn-primary btn-left">Download</a>
                                        {% for st in student %}
                                        <a href="{% url 'exam:review_exam' exam=ex.id student=st.id %}" class="btn btn-danger btn-right">Review</a>
                                        {% endfor %}
                                    </div>
                                    <!-- <p> Starts on : {{ ex.start_date_time }}</p> -->
                                </div>
                                {% endfor %}
                                <br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

        