exam/urls.py
from django.contrib import admin
from django.urls import path, include

from exam import views

app_name = 'exam'
urlpatterns = [
    path('mark/exam=<int:exam>/student=<int:student>', views.calculate_mark, name='calculate_mark'),
    path('exam/exam_id=<int:pk>', views.take_exam, name='take_exam'),
    path('review/exam_id=<int:exam>/student=<int:student>', views.review_exam, name='review_exam'),
    path('exam/pdf/exam_id=<int:exam>', views.generate_pdf, name='generate_pdf'),
    path('admin/exam/question/add_questions', views.add_questions, name="add_questions"),
    path('', views.main, name='main'),
]

exam_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.site.site_header = 'Admin Panel'
admin.site.site_title = 'Admin Panel'
admin.site.site_url = 'https://github.com/albatros-21'
admin.site.index_title = 'Admin Panel'
admin.empty_value_display = '**Empty**'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('exam.urls')),
]

if settings.DEBUG: # new
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path, include

from user import views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

user/models.py
from django.db import models
from django.core.validators import RegexValidator

class Year(models.Model):

    YEAR = (
        (1, 'First Year'),
        (2, 'Second Year'),
        (3, 'Third Year'),
        (4, 'Fourth Year'),
        (5, 'Fifth Year')
    )

    year  = models.IntegerField(
        choices=YEAR,
    )
    total_students = models.IntegerField()

    def __str__(self):
        message = self.get_year_display()
        return message

def get_image_path(instance, filename):
    return os.path.join('photos', filename)

class Student(models.Model):

    #RegexValidator used to check the given fields contain only alphanumeric characters
    alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')

    first_name = models.CharField(max_length = 150, validators=[alphanumeric])
    last_name  = models.CharField(max_length = 150, validators=[alphanumeric])
    year      = models.ForeignKey(Year, on_delete = models.DO_NOTHING)

    is_active = models.BooleanField(default=False)
    email_id   = models.EmailField()
    password   = models.CharField(max_length=255)

    def __str__(self):
        message = self.first_name + ' ' + self.last_name + ' (' + str(self.year) + ')'
        return message

user/forms.py
from django import forms

from .models import Student

class RegisterForm(forms.ModelForm):

    #Conditions added to ensure these fields contain only alphanumeric character and autocomplete off
    first_name = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'form-control' , 'autocomplete': 'off','pattern':'[A-Za-z ]+', 'title':'Enter Characters Only '}))
    last_name = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'form-control' , 'autocomplete': 'off','pattern':'[A-Za-z ]+', 'title':'Enter Characters Only '}))
    
    #To make Password field not visible use PasswordInput()
    password = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'form-control' , 'id': 'password','autocomplete': 'off'}))
    
    class Meta:
        model = Student
        fields = ('first_name', 'last_name','year','email_id', 'password',)


class LoginForm(forms.ModelForm):

    #To make Password field not visible use PasswordInput()
    password = forms.CharField(required=True,widget=forms.PasswordInput())

    class Meta:
        model = Student
        fields = ('email_id', 'password',)

user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from user.models import Student
from .forms import LoginForm, RegisterForm

from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .register.token import account_activation_token

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            
            # Saving registered value
            post = form.save()
            post.is_active = True
            post.save()

            #Sending confirmation mail 
            """ current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('user/acc_active_email.html', {
                    'user': post,
                    'domain': current_site.domain,
                    'uid':urlsafe_base64_encode(force_bytes(post.pk)),
                    'token':account_activation_token.make_token(post),
            })
            to_email = form.cleaned_data.get('email_id')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration') """
            return redirect('admin:index')
        else:
            message = 'Email id is already registered.'
            form = RegisterForm()
            return render(request, 'user/register.html', {'form': form, 'message':message})
    else:
        form = RegisterForm()
        return render(request, 'user/register.html', {'form': form})

def login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            data = request.POST.copy()
            email_id = data.get('email_id')
            password_entered = data.get('password')

            smail = Student.objects.filter(email_id__iexact=email_id, )
            password = smail.values('password')
            
            for word in password:
                if password_entered == word['password']:
                    response = redirect('exam:main')
                    response.set_cookie('username', email_id)
                    return response
            message = "Incorrect Email id or Password"
            form = LoginForm()
            return render(request, 'user/login.html', {'form': form, 'message':message})
        return redirect('user:login')
    else:
        if 'username' not in request.COOKIES:
            form = LoginForm()
            return render(request, 'user/login.html', {'form': form})
        else:
            return redirect('exam:main')

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Student.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('user:login')
    else:
        return HttpResponse('Activation link is invalid!')

def logout(request):
    response = redirect('user:login')
    response.delete_cookie('username')
    return response

user/templates/user/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
        <title>
            {% block title %} Oes {% endblock %}
        </title>
        <style>
            .oes-masthead {
                background-color: #EEEEEE;
                margin-bottom: 1em;
            }
        </style>

        {% block headers %} {% endblock %}
    </head>
    <body>
        <div class="oes-masthead">
            <div class="container">
                <nav class="nav">
                    <div class="navbar-brand">College Name</div>
                    <a class="nav-link" href="#">Profile</a>
                </nav>
            </div>
        </div>

        <div class='container'>
            <div class="row">
                <div class="col-sm-8 mymdb-main">
                    {% block main %} {% endblock %}
                </div>
                <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
                    {% block sidebar %} {% endblock %}
                </div>
            </div>
        </div>
    </body> 
</html>

user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title Page-->
    <title>Login</title>
    
    {% load staticfiles %}
    <!-- Icons font CSS-->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'user/css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <!-- Header -->
    <div class="oes-masthead">
        <div class="container">
            <nav class="nav">
                <div class="navbar-brand">College Name</div>
            </nav>
        </div>
    </div>

    <!-- Page body -->
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">            
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <center> <h2 class="title">Login</h2></center>

                    <!-- Displays Warnings -->
                    {% if message %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}

                    <!-- Login form generated by Django -->
                    <form method="POST" class="login-form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br />
                        <!--
                        <div class="alert alert-light" style="display: inline-block; padding-left:0px;" role="alert">
                            New to the site?  <a  href= "{% url 'user:register' %}" style="line-height:30px; padding:0px 10px; margin-left: 15px; font-size: small;" class="btn btn-secondary" >Register</a>
                        </div> -->

                        <button class="btn btn--radius-2 btn--blue" style="float: right;" type="submit" class="save btn btn-default">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% load staticfiles %}
    
    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'user/js/global.js' %}"></script>

</body>

</html>

user/templates/user/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title Page-->
    <title>Register</title>
    
    {% load static %}
    <!-- Icons font CSS-->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'user/css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <!-- Header -->
    <div class="oes-masthead">
        <div class="container">
            <nav class="nav">
                <center><div class="navbar-brand">College Name</div></center>
            </nav>
        </div>
    </div>

    <!-- Page body -->
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">            
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <center> <h2 class="title">Register</h2></center>

                    <!-- Warning message -->
                    {% if message %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
    
                    <!-- Form generated by Django -->
                    <form method="POST" class="register-form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button onclick="generatePassword()">Generate password</button>
                        <br />
                        <br />
                        <!-- <div class="alert alert-light" style="display: inline-block; padding-left:0px;" role="alert">
                            Already have an account?  <a  href= "{% url 'user:login' %}" style="line-height:30px; padding:0px 10px; margin-left: 15px; font-size: small;" class="btn btn-secondary" >Login</a>
                        </div> -->

                        <button class="btn btn--radius-2 btn--blue" style="float: right;" type="submit" class="save btn btn-default">Register</button>
                    </form>

                </div>
            </div>
        </div>
    </div>

    {% load static %}
    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'user/js/global.js' %}"></script>

</body>

<script>
    function generatePassword() {
        var password = Math.random().toString(36).slice(-10);
        document.getElementById("password").value = password;
    }
</script>
</html>